import '../../features/auth/domain/entities/user.dart';
import '../../features/machinery/domain/entities/machine.dart';
import '../../features/workers/domain/entities/worker.dart';
import '../../features/marketplace/domain/entities/product.dart';
import '../../features/bookings_orders/domain/entities/booking.dart';
import '../../features/bookings_orders/domain/entities/order.dart';
import '../../features/bookings_orders/domain/entities/order_item.dart';

class SampleData {
  static const User currentUser = User(
    id: 'user_1',
    name: 'bharath poojary',
    phone: '+91 8904089051',
    email: 'bharath.poojary@krushimithra.com',
    role: 'Farmer',
    profilePhoto: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?w=400',
    address: 'Green Farm House, Thirthahalli Road',
    locationName: 'Shivamogga, KA',
    latitude: 13.9299,
    longitude: 75.5681,
  );

  static final List<Machine> initialMachines = [
    Machine(
      id: 'm_1',
      name: 'Mahindra 575 DI Tractor (45 HP)',
      category: 'Tractors',
      ownerId: 'owner_101',
      ownerName: 'Suresh Patil',
      ownerPhone: '+91 8310856407',
      images: [
        'assets/images/mahindra_575_di.jpg',
      ],
      description: 'Heavy duty 45 HP Mahindra tractor with rotavator attachment. Perfect for deep ploughing, puddling, and crop transport.',
      rentalPricePerDay: 2200.0,
      location: 'Shivamogga, KA',
      latitude: 13.9300,
      longitude: 75.5680,
      isAvailable: true,
      rating: 4.8,
      reviewCount: 24,
      specs: {
        'Horse Power': '45 HP',
        'Fuel Type': 'Diesel',
        'Attachment Included': '5-Feet Rotavator',
        'Operator Included': 'Yes (Optional)',
      },
    ),
    Machine(
      id: 'm_2',
      name: 'Kubota Combine Harvester Pro-688',
      category: 'Harvesters',
      ownerId: 'owner_102',
      ownerName: 'Venkatesh Rao',
      ownerPhone: '+91 7204967137',
      images: [
        'assets/images/kubota_combine_harvester.jpg',
      ],
      description: 'High-speed paddy and wheat combine harvester. Complete grain harvesting with minimal loss and high fuel efficiency.',
      rentalPricePerDay: 5500.0,
      location: 'Chikamagaluru, KA',
      latitude: 13.3161,
      longitude: 75.7720,
      isAvailable: true,
      rating: 4.9,
      reviewCount: 18,
      specs: {
        'Cutter Bar Width': '2.0 meters',
        'Engine Power': '68 HP',
        'Crop Suitable': 'Paddy, Wheat, Soybeans',
        'Driver Status': 'Experienced Operator Provided',
      },
    ),
    Machine(
      id: 'm_3',
      name: 'VST Shakti 130 DI Power Tiller',
      category: 'Power Tillers',
      ownerId: 'owner_103',
      ownerName: 'Manjunatha K.',
      ownerPhone: '+91 8310080549',
      images: [
        'https://images.unsplash.com/photo-1589923188900-85dae523342b?w=800',
      ],
      description: 'Versatile 13 HP power tiller suitable for wet paddy field tilling, vegetable garden preparation, and narrow farm pathways.',
      rentalPricePerDay: 1200.0,
      location: 'Hassan, KA',
      latitude: 13.0033,
      longitude: 76.1004,
      isAvailable: true,
      rating: 4.6,
      reviewCount: 15,
      specs: {
        'Horse Power': '13 HP',
        'Tilling Width': '600 mm',
        'Fuel Consumption': '1.2 L/hr',
      },
    ),
    Machine(
      id: 'm_4',
      name: 'Honda 4-Stroke Heavy Duty Bush Cutter',
      category: 'Bush Cutters',
      ownerId: 'owner_104',
      ownerName: 'Ganesh Bhat',
      ownerPhone: '+91 9945583380',
      images: [
        'https://images.unsplash.com/photo-1617575521317-864339cd58a1?w=800',
      ],
      description: 'Portable grass and weed cutter machine for plantation maintenance, arecanut orchards, and edge clearing.',
      rentalPricePerDay: 600.0,
      location: 'Udupi, KA',
      latitude: 13.3409,
      longitude: 74.7421,
      isAvailable: true,
      rating: 4.7,
      reviewCount: 31,
      specs: {
        'Engine': '35cc 4-Stroke',
        'Weight': '7.5 kg',
        'Blade Type': '3-Tough Alloy Blade',
      },
    ),
    Machine(
      id: 'm_5',
      name: 'Borewell Rig Machine',
      category: 'Borewell Machines',
      ownerId: 'owner_105',
      ownerName: 'Ramesh G.',
      ownerPhone: '+91 9113664733',
      images: [
        'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=800',
      ],
      description: 'Heavy duty high-pressure hydraulic borewell drilling rig truck for agricultural water wells, casing pipe installation, and deep groundwater drilling.',
      rentalPricePerDay: 1800.0,
      location: 'Davanagere, KA',
      latitude: 14.4673,
      longitude: 75.9241,
      isAvailable: true,
      rating: 4.7,
      reviewCount: 12,
      isNew: true,
      specs: {
        'Drilling Depth': 'Up to 1000 ft',
        'Rig Type': 'Hydraulic Truck Rig',
        'Casing Pipe Diameter': '6.5 inches',
      },
    ),
  ];

  static final List<Worker> initialWorkers = [
    Worker(
      id: 'w_1',
      name: 'Basavarajappa M.',
      phone: '+91 7019064948',
      skills: ['Tractor Driver', 'Harvester Operator', 'Paddy Planter/Harvester'],
      experienceYears: 12,
      location: 'Shivamogga, KA',
      latitude: 13.9290,
      longitude: 75.5670,
      dailyRate: 900.0,
      isAvailable: true,
      rating: 4.9,
      reviewCount: 42,
      isVerified: true,
      profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
      bio: 'Expert tractor and combine harvester driver with 12+ years field experience across Malnad region farms.',
    ),
    Worker(
      id: 'w_2',
      name: 'Subramanya Bhat',
      phone: '+91 8217353139',
      skills: ['Arecanut Tree Climber/Harvester', 'Bush & Grass Cutting Specialist'],
      experienceYears: 8,
      location: 'Chikamagaluru, KA',
      latitude: 13.3150,
      longitude: 75.7710,
      dailyRate: 1100.0,
      isAvailable: true,
      rating: 4.95,
      reviewCount: 56,
      isVerified: true,
      profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
      bio: 'Professional arecanut harvester & spraying expert with safety harness equipment and high speed harvesting skills.',
    ),
    Worker(
      id: 'w_3',
      name: 'Kumar & Team (4 Workers)',
      phone: '+91 9019439854',
      skills: ['Paddy Planter/Harvester', 'General Farm Laborer'],
      experienceYears: 10,
      location: 'Mandya, KA',
      latitude: 12.5218,
      longitude: 76.8951,
      dailyRate: 2800.0, // Team rate per day
      isAvailable: true,
      rating: 4.7,
      reviewCount: 29,
      isVerified: true,
      profilePhoto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400',
      bio: 'Paddy transplanting & sugarcane cutting field labor team. Fast execution and well-disciplined farm workers.',
    ),
  ];

  static final List<Product> initialProducts = [
    // Farmer Produce Marketplace Items
    Product(
      id: 'p_1',
      title: 'Premium Quality Red Rashi Arecanut (Dry)',
      category: 'Arecanut',
      sellerId: 'user_201',
      sellerName: 'Narayana Hegde',
      sellerPhone: '+91 7892570830',
      images: [
        'https://images.unsplash.com/photo-1546430498-05c7b929fb30?w=800',
      ],
      description: 'Sun-dried high grade Malnad Rashi arecanut harvest. 100% organic processed without chemical dyes.',
      price: 480.0,
      unit: 'kg',
      quantityAvailable: 500,
      location: 'Shivamogga, KA',
      isAgroStoreItem: false,
      rating: 4.9,
    ),
    Product(
      id: 'p_2',
      title: 'Organic Malnad Black Pepper (Bold 550g/l)',
      category: 'Pepper',
      sellerId: 'user_202',
      sellerName: 'Annappa Gowda',
      sellerPhone: '+91 18296315071',
      images: [
        'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800',
      ],
      description: 'Fresh farm harvest black pepper. High essential oil aroma and bold grain size directly from plantation.',
      price: 650.0,
      unit: 'kg',
      quantityAvailable: 150,
      location: 'Chikamagaluru, KA',
      isAgroStoreItem: false,
      rating: 4.8,
    ),
    Product(
      id: 'p_3',
      title: 'Arabica Green Coffee Beans (Clean Processed)',
      category: 'Coffee',
      sellerId: 'user_203',
      sellerName: 'Estate Farmer Roy',
      sellerPhone: '+91 9900778825',
      images: [
        'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800',
      ],
      description: 'Direct estate single-origin Arabica coffee beans. Sun dried on patio with zero defects.',
      price: 320.0,
      unit: 'kg',
      quantityAvailable: 1200,
      location: 'Chikamagaluru, KA',
      isAgroStoreItem: false,
      rating: 4.7,
    ),

    // Agro Store Supplies Items
    Product(
      id: 'store_1',
      title: 'Hybrid Paddy Seeds - Jyothi High Yield (10 kg Bag)',
      category: 'Seeds',
      sellerId: 'store_admin',
      sellerName: 'Krushi Mithra Official Agro Store',
      sellerPhone: '+91 8000999000',
      images: [
        'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=800',
      ],
      description: 'Certified disease-resistant high yield paddy seed variety suitable for irrigated and rainfed conditions.',
      price: 850.0,
      unit: 'bag',
      quantityAvailable: 100,
      location: 'Shivamogga, KA',
      isAgroStoreItem: true,
      rating: 4.8,
    ),
    Product(
      id: 'store_2',
      title: 'IFFCO NPK 19-19-19 Water Soluble Fertiliser (5 kg)',
      category: 'Fertilisers',
      sellerId: 'store_admin',
      sellerName: 'Krushi Mithra Official Agro Store',
      sellerPhone: '+91 8000999000',
      images: [
        'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?w=800',
      ],
      description: '100% water soluble plant food for foliar spray and fertigation. Promotes healthy root growth and bumper yield.',
      price: 520.0,
      unit: 'pack',
      quantityAvailable: 250,
      location: 'Shivamogga, KA',
      isAgroStoreItem: true,
      rating: 4.9,
    ),
    Product(
      id: 'store_3',
      title: 'Neptune 16L Battery Operated Agri Knapsack Sprayer',
      category: 'Farming Tools',
      sellerId: 'store_admin',
      sellerName: 'Krushi Mithra Official Agro Store',
      sellerPhone: '+91 8000999000',
      images: [
        'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?w=800',
      ],
      description: '12V 8Ah battery powered crop sprayer with dual nozzle system and comfortable back padding.',
      price: 2450.0,
      unit: 'item',
      quantityAvailable: 45,
      location: 'Shivamogga, KA',
      isAgroStoreItem: true,
      rating: 4.75,
    ),
  ];

  static final List<Booking> initialBookings = [
    Booking(
      id: 'b_1001',
      bookingType: 'machine',
      targetId: 'm_1',
      targetTitle: 'Mahindra 575 DI Tractor (45 HP)',
      targetImageUrl: 'https://images.unsplash.com/photo-1592861956120-e524fc739696?w=800',
      customerId: 'user_1',
      customerName: 'bharath poojary',
      customerPhone: '+91 9876543210',
      providerId: 'owner_101',
      providerName: 'Suresh Patil',
      providerPhone: '+91 9845012345',
      startDate: DateTime.now().subtract(const Duration(days: 2)),
      endDate: DateTime.now().subtract(const Duration(days: 1)),
      totalAmount: 2200.0,
      paymentMethod: 'Cash on Delivery',
      paymentStatus: 'Paid',
      bookingStatus: 'Completed',
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      serviceLocation: 'Shivamogga, KA',
    ),
  ];

  static final List<Order> initialOrders = [
    Order(
      id: 'ord_5001',
      customerId: 'user_1',
      customerName: 'bharath poojary',
      customerPhone: '+91 9876543210',
      deliveryAddress: 'Green Farm House, Thirthahalli Road, Shivamogga',
      items: [
        OrderItem(
          product: initialProducts.firstWhere((p) => p.id == 'store_2'),
          quantity: 2,
          unitPrice: 520.0,
        ),
      ],
      totalAmount: 1040.0,
      paymentMethod: 'Pay on Delivery (COD)',
      paymentStatus: 'Pending',
      orderStatus: 'Confirmed',
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
  ];
}
